# -*- coding: utf-8 -*-
"""speechrecon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y96WLKsq-iYVpqtW-OsFdEoopPOokHWM
"""

pip install moviepy

pip install SpeechRecognition pydub

import speech_recognition as sr
from IPython.display import Audio
from moviepy.editor import *
import os

Audio("chmlk.wav")

filename=input("Your Audio File : ")+".wav"

if "Audio_Chunks" not in os.listdir() :
  os.mkdir("Audio_Chunks")

wholeclip=AudioFileClip(filename)
i=0.0
l=1
while i< wholeclip.end :
  if i+10<wholeclip.end:
    wholeclip.subclip(i,i+10).write_audiofile(os.getcwd()+"/Audio_Chunks/"+f"{filename[:-4]}{l}.wav")
  else :
    wholeclip.subclip(i,wholeclip.end).write_audiofile(os.getcwd()+"/Audio_Chunks/"+f"{filename[:-4]}{l}.wav")
  i=i+10
  l=l+1

audch=list(filter(lambda x:x.endswith(".wav"),os.listdir(f'{os.getcwd()}/Audio_Chunks/')))

audch

if "Text_Chunks" not in os.listdir() :
  os.mkdir("Text_Chunks")

def textmaker(filename):
  r=sr.Recognizer()
  with sr.AudioFile(filename) as source:
      audio_data = r.record(source)
      text = r.recognize_google(audio_data)
      return text

for filename in audch:
  txtfile=f'{os.getcwd()}/Text_Chunks/{filename[:-4]}.txt'
  f=open(txtfile,'w')
  f.write(textmaker(f"{os.getcwd()}/Audio_Chunks/{filename}"))
  f.close()
#f=open("mlt.txt",'r')
#print(f.read())
#f.close()

for filename in list(filter(lambda x:x.endswith(".txt"),os.listdir(f'{os.getcwd()}/Text_Chunks/'))):
  txtfile=f'{os.getcwd()}/Text_Chunks/{filename}'
  f=open(txtfile,'r')
  print(f"{filename} is : {f.read()}")
  f.close()

filename=input("Enter the name of the file to be converted : ")
filename=filename+".mp4"
vidclip=VideoFileClip(filename)#creates video clip object
audfile=input("Enter the name of your audio file : ")+".wav" 
vidclip.audio.write_audiofile(audfile)#extracts audio and writes the clip as an audio file

textmaker("chirag2.wav")

"""A little bit about the os module : Its a way to allow python to interact with the operating system especially its file directories.

Note : when files are reffered to by their names in python : they are in the current working directory. ie In the content directory in google colab.

CWD: is also the folder in which python is operating. It starts at '/content' but can be changed using chdir(path string)
"""

import os
os.getcwd()#returns a path string of the cwd.

os.chdir("/content/sample_data")
os.getcwd()

"""Making a directory will make a new folder in our directory net. we take an relative/ absolute path with the foler to be creaed at the end creating a new folder. """

os.mkdir("Geeks")

"""List Dir :- in CWD"""

#os.chdir("/content")
os.listdir()
os.listdir("/content/sample_data")